/**
 * API Service for AI Call Intelligence Platform
 * REAL DATA ONLY - All endpoints connect to OpenAI-powered backend
 * NO MOCK DATA - Everything comes from actual call transcriptions and analysis
 */

const API_BASE_URL = import.meta.env.VITE_API_URL || 'https://ai-calling-intelligence.onrender.com';

export interface ApiResponse<T = any> {
  success: boolean;
  data?: T;
  error?: string;
  message?: string;
  pagination?: {
    total: number;
    skip: number;
    limit: number;
    has_more: boolean;
  };
}

// API call wrapper with better error handling
async function apiCall<T = any>(
  endpoint: string,
  options: RequestInit = {}
): Promise<ApiResponse<T>> {
  try {
    const response = await fetch(`${API_BASE_URL}${endpoint}`, {
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
      ...options,
    });

    const data = await response.json();

    if (!response.ok) {
      return {
        success: false,
        error: data.detail || data.error || 'API request failed',
      };
    }

    // Handle different response formats
    if (data.success !== undefined) {
      return data;
    }

    return {
      success: true,
      data: data,
    };
  } catch (error) {
    console.error('API Error:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Network connection failed',
    };
  }
}

// Real API endpoints - no mock data
export const api = {
  // === REAL AUDIO PROCESSING WITH OPENAI ===
  
  /**
   * Process audio file with real OpenAI Whisper transcription and GPT analysis
   * Stores results in database - replaces all sample data
   */
  async processAudio(audioFile: File, title?: string, description?: string): Promise<ApiResponse> {
    const formData = new FormData();
    formData.append('file', audioFile);
    if (title) formData.append('title', title);
    if (description) formData.append('description', description);

    return apiCall('/api/audio/process-complete', {
      method: 'POST',
      body: formData,
      headers: {}, // Remove Content-Type to let browser set it for FormData
    });
  },

  /**
   * Transcribe audio only (real Whisper API)
   */
  async transcribeAudio(audioFile: File): Promise<ApiResponse> {
    const formData = new FormData();
    formData.append('file', audioFile);

    return apiCall('/api/audio/transcribe-audio', {
      method: 'POST',
      body: formData,
      headers: {}, // Remove Content-Type for FormData
    });
  },

  /**
   * Analyze transcript with GPT (real analysis)
   */
  async analyzeTranscript(transcript: string): Promise<ApiResponse> {
    return apiCall('/api/audio/analyze-transcript', {
      method: 'POST',
      body: JSON.stringify({ transcript }),
    });
  },

  // === REAL CALLS DATA FROM DATABASE ===
  
  /**
   * Get calls from real database (no mock data)
   * All calls come from actual audio uploads and OpenAI analysis
   */
  async getCalls(params?: {
    skip?: number;
    limit?: number;
    sentiment?: string;
    search?: string;
  }): Promise<ApiResponse> {
    const searchParams = new URLSearchParams();
    if (params?.skip) searchParams.append('skip', params.skip.toString());
    if (params?.limit) searchParams.append('limit', params.limit.toString());
    if (params?.sentiment) searchParams.append('sentiment', params.sentiment);
    if (params?.search) searchParams.append('search', params.search);

    const queryString = searchParams.toString();
    return apiCall(`/api/calls${queryString ? '?' + queryString : ''}`);
  },

  /**
   * Get detailed call information with real analysis results
   */
  async getCallDetail(callId: number): Promise<ApiResponse> {
    return apiCall(`/api/calls/${callId}`);
  },

  /**
   * Get real dashboard analytics calculated from actual call data
   * NO sample data - everything computed from real OpenAI analysis
   */
  async getDashboardAnalytics(): Promise<ApiResponse> {
    return apiCall('/api/calls/analytics/dashboard');
  },

  // === REAL ACTION ITEMS FROM AI ANALYSIS ===
  
  /**
   * Get action items generated by AI from real call transcripts
   */
  async getActionItems(params?: {
    skip?: number;
    limit?: number;
    status?: string;
    priority?: string;
    call_id?: number;
  }): Promise<ApiResponse> {
    const searchParams = new URLSearchParams();
    if (params?.skip) searchParams.append('skip', params.skip.toString());
    if (params?.limit) searchParams.append('limit', params.limit.toString());
    if (params?.status) searchParams.append('status', params.status);
    if (params?.priority) searchParams.append('priority', params.priority);
    if (params?.call_id) searchParams.append('call_id', params.call_id.toString());

    const queryString = searchParams.toString();
    return apiCall(`/api/action-items${queryString ? '?' + queryString : ''}`);
  },

  /**
   * Get detailed action item with call context
   */
  async getActionItemDetail(actionItemId: number): Promise<ApiResponse> {
    return apiCall(`/api/action-items/${actionItemId}`);
  },

  /**
   * Update action item status
   */
  async updateActionItemStatus(actionItemId: number, status: string): Promise<ApiResponse> {
    return apiCall(`/api/action-items/${actionItemId}/status?status=${status}`, {
      method: 'PATCH',
    });
  },

  /**
   * Get action items analytics from real data
   */
  async getActionItemsAnalytics(): Promise<ApiResponse> {
    return apiCall('/api/action-items/analytics/summary');
  },

  // === UTILITY FUNCTIONS ===
  
  /**
   * Health check endpoint
   */
  async healthCheck(): Promise<ApiResponse> {
    return apiCall('/api/health');
  },
};

// Export the main API object as default
export default api;