/**
 * Real Data Types and Interfaces
 * NO MOCK DATA - Only type definitions for real OpenAI analysis results
 */

// Real Call Analysis Data (from OpenAI)
export interface RealCall {
  id: number;
  title: string;
  description?: string;
  transcript: string;  // Full Whisper transcription
  audio_filename?: string;
  duration_seconds?: number;
  
  // Real OpenAI sentiment analysis
  overall_sentiment: 'positive' | 'negative' | 'neutral' | 'mixed';
  sentiment_confidence: number;
  positive_percentage: number;
  negative_percentage: number;
  neutral_percentage: number;
  
  // AI generated content
  ai_summary?: string;
  key_topics: string[];
  recommendations: string[];
  
  // Real extracted data
  pain_points: RealPainPoint[];
  action_items: RealActionItem[];
  
  // Metadata
  tokens_used: number;
  openai_model_used: string;
  whisper_model_used: string;
  created_at: string;
  updated_at?: string;
}

// Real Pain Points (extracted by AI)
export interface RealPainPoint {
  id: number;
  call_id: number;
  description: string;  // AI extracted description
  category: string;  // AI categorized: pricing|product|service|delivery|communication|technical|other
  severity: 'low' | 'medium' | 'high' | 'critical';  // AI assessed severity
  confidence_score: number;  // AI confidence in extraction
  transcript_segment?: string;  // Relevant quote from transcript
  created_at: string;
}

// Real Action Items (generated by AI)
export interface RealActionItem {
  id: number;
  call_id: number;
  title: string;  // AI generated title
  description: string;  // AI generated description
  priority: 'low' | 'medium' | 'high' | 'urgent';  // AI assessed priority
  status: 'pending' | 'in_progress' | 'completed' | 'cancelled';
  category: string;  // AI categorized: follow_up|research|documentation|training|escalation|communication|other
  estimated_days?: number;  // AI estimated timeline
  assigned_to?: string;
  due_date?: string;
  completed_at?: string;
  created_at: string;
  updated_at?: string;
  call: {
    id: number;
    title: string;
    sentiment: string;
  };
}

// Real Dashboard Analytics (calculated from actual data)
export interface RealDashboardAnalytics {
  overview: {
    total_calls: number;
    calls_last_30_days: number;
    calls_last_7_days: number;
    total_pain_points: number;
    total_action_items: number;
    avg_sentiment_confidence: number;
  };
  sentiment_distribution: Record<string, number>;
  pain_point_categories: { category: string; count: number }[];
  action_item_priorities: { priority: string; count: number }[];
  recent_calls: {
    id: number;
    title: string;
    sentiment: string;
    pain_points: number;
    action_items: number;
    created_at: string;
  }[];
  monthly_trends: {
    month: string;
    calls: number;
    pain_points: number;
    action_items: number;
  }[];
  generated_at: string;
  data_source: 'real_openai_analysis';
}

// Real Audio Processing Results
export interface AudioProcessingResult {
  success: boolean;
  call_id?: number;
  filename: string;
  transcription: {
    transcript: string;
    filename: string;
    file_size: number;
    model_used: string;
  };
  analysis: {
    overall_sentiment: string;
    confidence_score: number;
    pain_points: Array<{
      description: string;
      category: string;
      severity: string;
      confidence: number;
    }>;
    action_items: Array<{
      title: string;
      description: string;
      priority: string;
      category: string;
      estimated_days: number;
    }>;
    key_topics: string[];
    summary: string;
    recommendations: string[];
  };
  pain_points_saved: number;
  action_items_saved: number;
  total_tokens_used: number;
  message: string;
}

// API Response wrapper
export interface ApiResponse<T = any> {
  success: boolean;
  data?: T;
  error?: string;
  message?: string;
  pagination?: {
    total: number;
    skip: number;
    limit: number;
    has_more: boolean;
  };
}

// Real-time data state (no mock data fallbacks)
export interface RealDataState {
  calls: RealCall[];
  actionItems: RealActionItem[];
  dashboardAnalytics: RealDashboardAnalytics | null;
  isLoading: boolean;
  error: string | null;
  lastUpdated: string | null;
}

// Chart data from real analysis
export interface RealChartData {
  labels: string[];
  datasets: {
    label: string;
    data: number[];
    backgroundColor?: string | string[];
    borderColor?: string;
  }[];
}

// Types are already exported inline above