"""
Action Items API routes - Real data from OpenAI analysis
Returns action items generated by AI from actual call transcriptions
"""
from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy.orm import Session
from sqlalchemy import desc, func, and_, or_
from typing import List, Optional, Dict, Any
from datetime import datetime, date
from loguru import logger

from app.core.database import get_db
from app.models import ActionItem, Call, ActionItemPriority, ActionItemStatus

router = APIRouter()

@router.get("/")
async def get_action_items(
    db: Session = Depends(get_db),
    skip: int = Query(0, ge=0),
    limit: int = Query(20, ge=1, le=100),
    status: Optional[str] = Query(None),
    priority: Optional[str] = Query(None),
    call_id: Optional[int] = Query(None)
):
    """
    Get action items from real AI analysis
    No mock data - returns actual action items generated by OpenAI from call transcripts
    """
    try:
        query = db.query(ActionItem)
        
        # Filter by status if provided
        if status and status in ['pending', 'in_progress', 'completed', 'cancelled']:
            query = query.filter(ActionItem.status == status)
        
        # Filter by priority if provided
        if priority and priority in ['low', 'medium', 'high', 'urgent']:
            query = query.filter(ActionItem.priority == priority)
        
        # Filter by specific call if provided
        if call_id:
            query = query.filter(ActionItem.call_id == call_id)
        
        # Get total count
        total = query.count()
        
        # Get action items with pagination
        action_items = query.order_by(desc(ActionItem.created_at)).offset(skip).limit(limit).all()
        
        # Format response with real data
        action_items_data = []
        for item in action_items:
            # Get related call info
            call_info = db.query(Call).filter(Call.id == item.call_id).first()
            
            action_items_data.append({
                "id": item.id,
                "title": item.title,  # AI generated title
                "description": item.description,  # AI generated description
                "priority": item.priority.value if item.priority else "medium",
                "status": item.status.value if item.status else "pending",
                "category": item.category,  # AI categorized
                "estimated_days": item.estimated_days,  # AI estimated
                "assigned_to": item.assigned_to,
                "due_date": item.due_date.isoformat() if item.due_date else None,
                "completed_at": item.completed_at.isoformat() if item.completed_at else None,
                "created_at": item.created_at.isoformat() if item.created_at else None,
                "updated_at": item.updated_at.isoformat() if item.updated_at else None,
                "call": {
                    "id": item.call_id,
                    "title": call_info.title if call_info else "Unknown Call",
                    "sentiment": call_info.overall_sentiment.value if call_info and call_info.overall_sentiment else "neutral"
                }
            })
        
        return {
            "success": True,
            "data": action_items_data,
            "pagination": {
                "total": total,
                "skip": skip,
                "limit": limit,
                "has_more": skip + limit < total
            }
        }
        
    except Exception as e:
        logger.error(f"Error fetching action items: {str(e)}")
        raise HTTPException(status_code=500, detail=f"Error fetching action items: {str(e)}")

@router.get("/{action_item_id}")
async def get_action_item_detail(action_item_id: int, db: Session = Depends(get_db)):
    """
    Get detailed action item information with call context
    """
    try:
        action_item = db.query(ActionItem).filter(ActionItem.id == action_item_id).first()
        if not action_item:
            raise HTTPException(status_code=404, detail="Action item not found")
        
        # Get related call information
        call = db.query(Call).filter(Call.id == action_item.call_id).first()
        
        return {
            "success": True,
            "data": {
                "id": action_item.id,
                "title": action_item.title,
                "description": action_item.description,
                "priority": action_item.priority.value if action_item.priority else "medium",
                "status": action_item.status.value if action_item.status else "pending",
                "category": action_item.category,
                "estimated_days": action_item.estimated_days,
                "assigned_to": action_item.assigned_to,
                "due_date": action_item.due_date.isoformat() if action_item.due_date else None,
                "completed_at": action_item.completed_at.isoformat() if action_item.completed_at else None,
                "created_at": action_item.created_at.isoformat() if action_item.created_at else None,
                "updated_at": action_item.updated_at.isoformat() if action_item.updated_at else None,
                "call": {
                    "id": call.id if call else None,
                    "title": call.title if call else "Unknown Call",
                    "transcript_preview": call.transcript[:300] + "..." if call and len(call.transcript) > 300 else (call.transcript if call else ""),
                    "sentiment": call.overall_sentiment.value if call and call.overall_sentiment else "neutral",
                    "created_at": call.created_at.isoformat() if call and call.created_at else None
                }
            }
        }
        
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error fetching action item detail: {str(e)}")
        raise HTTPException(status_code=500, detail=f"Error fetching action item: {str(e)}")

@router.patch("/{action_item_id}/status")
async def update_action_item_status(
    action_item_id: int,
    status: str,
    db: Session = Depends(get_db)
):
    """
    Update action item status
    """
    try:
        if status not in ['pending', 'in_progress', 'completed', 'cancelled']:
            raise HTTPException(status_code=400, detail="Invalid status")
        
        action_item = db.query(ActionItem).filter(ActionItem.id == action_item_id).first()
        if not action_item:
            raise HTTPException(status_code=404, detail="Action item not found")
        
        # Update status
        action_item.status = ActionItemStatus(status)
        if status == 'completed':
            action_item.completed_at = datetime.now()
        
        db.commit()
        db.refresh(action_item)
        
        return {
            "success": True,
            "message": f"Action item status updated to {status}",
            "data": {
                "id": action_item.id,
                "status": action_item.status.value,
                "completed_at": action_item.completed_at.isoformat() if action_item.completed_at else None
            }
        }
        
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error updating action item status: {str(e)}")
        raise HTTPException(status_code=500, detail=f"Error updating status: {str(e)}")

@router.get("/analytics/summary")
async def get_action_items_analytics(db: Session = Depends(get_db)):
    """
    Get action items analytics from real data
    """
    try:
        # Status distribution
        status_stats = db.query(
            ActionItem.status,
            func.count(ActionItem.id).label('count')
        ).group_by(ActionItem.status).all()
        
        # Priority distribution
        priority_stats = db.query(
            ActionItem.priority,
            func.count(ActionItem.id).label('count')
        ).group_by(ActionItem.priority).all()
        
        # Category distribution
        category_stats = db.query(
            ActionItem.category,
            func.count(ActionItem.id).label('count')
        ).group_by(ActionItem.category).order_by(func.count(ActionItem.id).desc()).all()
        
        return {
            "success": True,
            "data": {
                "total_action_items": db.query(ActionItem).count(),
                "status_distribution": [
                    {"status": status.value if status else "pending", "count": count}
                    for status, count in status_stats
                ],
                "priority_distribution": [
                    {"priority": priority.value if priority else "medium", "count": count}
                    for priority, count in priority_stats
                ],
                "category_distribution": [
                    {"category": category or "other", "count": count}
                    for category, count in category_stats
                ],
                "generated_at": datetime.now().isoformat(),
                "data_source": "real_ai_generated"
            }
        }
        
    except Exception as e:
        logger.error(f"Error generating action items analytics: {str(e)}")
        raise HTTPException(status_code=500, detail=f"Error generating analytics: {str(e)}")